### ISSUE TITLE
Proposal: A more standard gulpfile

### ISSUE THREAD

**Issue by arturmuller** [saamo/api-blueprint-focus-booster#2]
**Warning: I am totally nitpicking here...**

I think that a more standard gulpfile would make it easier to understand this project. Fundamentally this thing is a collection of gulp plugins plus corresponding folder structure. The first thing I wanted to do when I opened this was to check out what gulp actually does here. Unfortunately I had to click through a whole bunch of files, most of which contain almost not code. :(

I think splitting out your gulpfile is good when you are working on a huge project but for here I feel it might be over-abstracted given the relatively low complexity. Plus, one less folder makes it neater and clearer which are the parts you actually *should* be messing with...

Whatcha think?

**Comment by saamo** [comment]
You're totally right. I chose more proactive approach to be prepared for complexity but it didn't come. One gulpfile is way to go here.

**Comment by arturmuller** [comment]
:+1:

**Comment by saamo** [comment]
Updated. Thank you!
