### ISSUE TITLE
Proposal: Yeoman generator

### ISSUE THREAD

**Issue by arturmuller** [saamo/api-blueprint-focus-booster#3]
What do you think about a [Yeoman generator](http://yeoman.io/) based on this repo?

I was thinking that would be an elegant way to create the scaffold without having to manually get rid of Git leftovers in the repo. (I mean: when you clone the repo, you have the entire git history left behind which you should probably remove if you don't wanna make a mess...)

**Comment by saamo** [comment]
Scaffolding is definitely the way to go when having this kind of project (removing Git files, handling config files, etc.). The problem which is more actual to me is how to solve updating the project. I was about to use [Slush](http://slushjs.github.io/) but Yeoman supports updating generators which is nice!

**Comment by arturmuller** [comment]
Slush looks very cool! How did I never hear about it before? :O

What do you mean by the 'updating'? You mean that the user has to remember to manually say they want to update the local global slush generator package to get a new version? As in, it doesn't happen automatically when you use the Slush command?

**Comment by saamo** [comment]
I wasn't clear enough. By “updating the project” I meant updating already created project without affecting files created/deleted by user.

Take the src directory. There are some example files (`_header.apib` and `user.apib`) so you can try to run tasks directly after it's installed to see some results. But when you start putting your files inside src directory, you don't want to have those example files there anymore so you delete them. Unfortunately when you run generator again for update (doesn't matter if it's Slush or Yeoman – they seem to work the same way), it will copy those files there again which is not the desired behavior. And similar problem comes with the config file.

**Comment by arturmuller** [comment]
Oh, like you want to update the gulp tasks whilst you already have existing API blueprints in the folder structure?

Couple of ideas:

1. With Slush, since it's just Gulp, I think it should be possible to check whether there are some files in the source folder and only copy over the example files if the directory doesn't exist/it's empty. But maybe that's too complicated/magic.
2. Maybe Slush could have a special 'update' task that replaces the gulpfile, but doesn't worry about the examples.
3. Maybe Slash has two commands for the scaffold — 'build', and 'build with examples'? That way it is clearer which one does what. (I like this the most)
3. Lastly, talking about this repo, I think you could just completely move the examples to their own directory (examples) and that way the live things are always clean. I've seen the 'examples' approach in various repos and I like it because it is super clear. Once you are done with it, you can just remove that folder and be done with it.

Overall I think I wouldn't worry about this scenario though. I don't think it is super likely, and either way: copy/pasting a single gulpfile from this repo is imo the easiest way to 'update' your tasks.

**Comment by saamo** [comment]
I don't think that Slush (neither Yeoman) has the ability to run different commands for a generator. Therefore I would go, for the sake of simplicity, with the last proposed solution – to have example blueprints in separate folder and run `gulp example` to generate output file from these files and not from files inside the src folder. But after every update the example folder would be present which I wouldn't like personally.

**Comment by saamo** [comment]
Or even better – you can use [inquirer](https://www.npmjs.com/package/inquirer) plugin to ask user a question. So the question would be ‘Install with examples?’ and the default answer would be ‘yN‘.

**Comment by saamo** [comment]
Solved with [Slush generator](https://www.npmjs.com/package/slush-api-blueprint-focus-booster). Thanks!
