### ISSUE TITLE
There is no documentation

### ISSUE THREAD

**Issue by inovakov** [saamo/api-blueprint-focus-booster#5]
... how to actually prepare the API Blueprint files...

**Comment by saamo** [comment]
https://github.com/saamo/api-blueprint-focus-booster#usage

Look into `src` folder. There are two files which will be used to generate one API Blueprint.

Btw the preferred way is to use the Slush generator which will generates project structure for you with example files.

**Comment by inovakov** [comment]
The README says:

```
Substitutes commonly used values (templating).
```

How can I do this? Where and how should I put the "commonly used values"?

Or:
```
Concatenates all files into one output file.
```

What is the order, how can I configure/manage the concatenation?

**Comment by saamo** [comment]
**Substitutions**

You can define variables in the config file (copy the example `config.example.js` to `config.js`). There are already some predefined variables.

```json
"user": {
  "firstName": "John",
  "lastName": "Dope",
  "email": "john.dope@domain.com"
}
```

Then you can use them inside blueprints like in this example JSON response:

```json
{
  "email": "<%= user.email %>",
  "firstName": "<%= user.firstName %>",
  "lastName": "<%= user.lastName %>"
}
```

I think it's quite self-explanatory when you look into `src` directory and into the config file.

**Concatenation**

This task is not configurable yet – files are taken in alphabetical order. If you want to change the order of your blueprints, name them properly (_1-blueprint.apib_, _2-blueprint.apib_, etc.). You can also put them in separate folders.

**Comment by arturmuller** [comment]
I think this stuff should probably be in the Readme. I think that is much easier to understand for people who just stumbled on the repo than relying on the end-user to dig into the source. BTW @inovakov — I am curious whether the above answered your question?

**Comment by saamo** [comment]
I agree it could be documented better. What else is not clear to you?

(And just for your information, I'm planning to make the concatenation task configurable.)

**Comment by inovakov** [comment]
Yes, thanks for the clarification.

I was evaluating quite a large list of API Blueprint related tools, so I didn't have time to examine the source code. I think, that just a few lines more in the README can make it much easier for newcomers like me to understand, how the tool works.

**Comment by saamo** [comment]
Thank you both for your feedbackl @inovakov, can I ask you which tool(s) you have chosen then?
